export const PARK_FACTORS = {
  COL: { hr: 1.35, hit: 1.15, k: 0.93, label: "Hitter Haven"   },
  CIN: { hr: 1.15, hit: 1.05, k: 0.97, label: "Hitter-Friendly"},
  PHI: { hr: 1.10, hit: 1.04, k: 0.98, label: "Hitter-Friendly"},
  BOS: { hr: 1.08, hit: 1.09, k: 0.97, label: "Hitter-Friendly"},
  TEX: { hr: 1.08, hit: 1.03, k: 0.98, label: "Hitter-Friendly"},
  BAL: { hr: 1.07, hit: 1.03, k: 0.99, label: "Hitter-Friendly"},
  CHC: { hr: 1.04, hit: 1.02, k: 0.99, label: "Neutral (wind-variable)" },
  NYY: { hr: 1.05, hit: 1.01, k: 1.00, label: "Slight Hitter"  },
  TOR: { hr: 1.03, hit: 1.02, k: 1.00, label: "Slight Hitter"  },
  ARI: { hr: 1.02, hit: 1.01, k: 0.99, label: "Slight Hitter"  },
  ATL: { hr: 1.02, hit: 1.01, k: 1.00, label: "Neutral"        },
  DET: { hr: 1.01, hit: 1.00, k: 1.00, label: "Neutral"        },
  MIL: { hr: 1.00, hit: 1.01, k: 1.00, label: "Neutral"        },
  CHW: { hr: 1.00, hit: 1.00, k: 1.00, label: "Neutral"        },
  STL: { hr: 0.98, hit: 0.99, k: 1.01, label: "Slight Pitcher" },
  WSH: { hr: 0.98, hit: 0.99, k: 1.00, label: "Slight Pitcher" },
  MIN: { hr: 0.97, hit: 0.99, k: 1.01, label: "Slight Pitcher" },
  CLE: { hr: 0.97, hit: 0.99, k: 1.00, label: "Slight Pitcher" },
  PIT: { hr: 0.96, hit: 0.98, k: 1.01, label: "Pitcher-Friendly"},
  NYM: { hr: 0.96, hit: 0.98, k: 1.01, label: "Pitcher-Friendly"},
  LAA: { hr: 0.96, hit: 0.98, k: 1.01, label: "Pitcher-Friendly"},
  HOU: { hr: 0.95, hit: 0.99, k: 1.01, label: "Pitcher-Friendly"},
  MIA: { hr: 0.94, hit: 0.98, k: 1.02, label: "Pitcher-Friendly"},
  TB:  { hr: 0.94, hit: 0.97, k: 1.02, label: "Pitcher-Friendly"},
  OAK: { hr: 0.93, hit: 0.97, k: 1.01, label: "Pitcher-Friendly"},
  LAD: { hr: 0.93, hit: 0.97, k: 1.02, label: "Pitcher-Friendly"},
  KC:  { hr: 0.91, hit: 0.98, k: 1.01, label: "Pitcher-Friendly"},
  SEA: { hr: 0.90, hit: 0.97, k: 1.02, label: "Pitcher-Friendly"},
  SD:  { hr: 0.87, hit: 0.96, k: 1.03, label: "Pitcher Haven"  },
  SF:  { hr: 0.83, hit: 0.96, k: 1.03, label: "Pitcher Haven"  },
};

export const NEUTRAL_PARK = { hr: 1.0, hit: 1.0, k: 1.0, label: "Neutral" };

export const HOME_FIELD_ADV = {
  BOS: [6, 5, 3],
  LAD: [5, 4, 3],
  HOU: [5, 4, 3],
  ATL: [5, 4, 3],
  NYY: [5, 4, 2],
  COL: [5, 4, 3],
  CHC: [5, 3, 2],
  PHI: [4, 3, 2],
  STL: [4, 3, 2],
  MIL: [4, 3, 2],
  SF:  [4, 3, 2],
  MIN: [4, 3, 2],
  CIN: [4, 3, 2],
  DET: [3, 3, 2],
  TEX: [3, 3, 2],
  BAL: [3, 3, 2],
  NYM: [3, 2, 2],
  PIT: [3, 2, 2],
  CLE: [3, 2, 2],
  SEA: [3, 2, 2],
  KC:  [3, 2, 2],
  WSH: [3, 2, 2],
  LAA: [3, 2, 2],
  CHW: [3, 2, 2],
  ARI: [3, 2, 2],
  SD:  [3, 2, 2],
  OAK: [3, 2, 1],
  TB:  [3, 2, 1],
  MIA: [2, 2, 1],
};

export const DEFAULT_HOME_ADV = [4, 3, 2];

export const MODEL_TIER = (score) =>
  score >= 65 ? "HIGH" : score >= 56 ? "MEDIUM" : "SPEC";

export const UMPIRE_STATS = {
  "Pat Hoberg":         { kRate: "23.4%", bbRate: "7.3%", tendency: "Wide zone — among highest K rates in MLB", rating: "pitcher" },
  "Dan Bellino":        { kRate: "22.8%", bbRate: "7.6%", tendency: "Wide zone — high K environment", rating: "pitcher" },
  "Roberto Ortiz":      { kRate: "22.6%", bbRate: "7.8%", tendency: "Expansive zone — favors strikeout pitchers", rating: "pitcher" },
  "Nic Lentz":          { kRate: "22.5%", bbRate: "7.9%", tendency: "Wide zone — suppresses walks", rating: "pitcher" },
  "Cory Blaser":        { kRate: "22.4%", bbRate: "7.5%", tendency: "Wide zone — low BB, high K", rating: "pitcher" },
  "Adam Hamari":        { kRate: "22.3%", bbRate: "7.8%", tendency: "Consistent wide zone — K props lean over", rating: "pitcher" },
  "Tom Hallion":        { kRate: "22.2%", bbRate: "7.9%", tendency: "Wide zone — favors strikeout pitchers", rating: "pitcher" },
  "Mike Muchlinski":    { kRate: "22.1%", bbRate: "8.0%", tendency: "Wide zone — K environment", rating: "pitcher" },
  "Ryan Additon":       { kRate: "22.0%", bbRate: "8.0%", tendency: "Above-average zone — slight K lean", rating: "pitcher" },
  "Will Little":        { kRate: "22.0%", bbRate: "8.0%", tendency: "Wide zone — favors power pitchers", rating: "pitcher" },
  "Mark Wegner":        { kRate: "22.0%", bbRate: "8.1%", tendency: "Wide zone — above-average K rate", rating: "pitcher" },
  "Quinn Wolcott":      { kRate: "22.0%", bbRate: "8.0%", tendency: "Wide zone — slightly favors pitchers", rating: "pitcher" },
  "Edwin Moscoso":      { kRate: "21.9%", bbRate: "8.0%", tendency: "Slightly wide zone — above-average K rate", rating: "pitcher" },
  "Ben May":            { kRate: "21.9%", bbRate: "8.0%", tendency: "Wide zone — favors high-K starters", rating: "pitcher" },
  "Sean Barber":        { kRate: "21.8%", bbRate: "8.0%", tendency: "Slightly expanded zone", rating: "pitcher" },
  "James Hoye":         { kRate: "21.8%", bbRate: "8.1%", tendency: "Above-average K zone", rating: "pitcher" },
  "Mike Estabrook":     { kRate: "21.8%", bbRate: "8.0%", tendency: "Wide zone — K props lean over", rating: "pitcher" },
  "David Rackley":      { kRate: "21.7%", bbRate: "8.1%", tendency: "Slightly wide zone", rating: "pitcher" },
  "Alfonso Marquez":    { kRate: "21.7%", bbRate: "8.0%", tendency: "Wide zone — consistent calls", rating: "pitcher" },
  "Manny Gonzalez":     { kRate: "21.6%", bbRate: "8.0%", tendency: "Slightly expanded zone", rating: "pitcher" },
  "Tom Woodring":       { kRate: "21.6%", bbRate: "8.0%", tendency: "Above-average zone size", rating: "pitcher" },
  "Rob Drake":          { kRate: "21.5%", bbRate: "8.2%", tendency: "Slightly wide zone — reliable calls", rating: "pitcher" },
  "Gabe Morales":       { kRate: "21.2%", bbRate: "8.5%", tendency: "Average zone — neutral for props", rating: "neutral" },
  "Brian Knight":       { kRate: "21.2%", bbRate: "8.4%", tendency: "Consistent neutral zone", rating: "neutral" },
  "Vic Carapazza":      { kRate: "21.1%", bbRate: "8.3%", tendency: "Average zone size — neutral calls", rating: "neutral" },
  "Fieldin Culbreth":   { kRate: "21.1%", bbRate: "8.5%", tendency: "Neutral zone — very consistent", rating: "neutral" },
  "Andy Fletcher":      { kRate: "21.1%", bbRate: "8.3%", tendency: "Average zone — steady calls", rating: "neutral" },
  "Alan Porter":        { kRate: "21.0%", bbRate: "8.5%", tendency: "Average zone — neutral for K and BB props", rating: "neutral" },
  "Chris Guccione":     { kRate: "21.0%", bbRate: "8.3%", tendency: "Average zone — reliable umpire", rating: "neutral" },
  "Phil Cuzzi":         { kRate: "21.0%", bbRate: "8.4%", tendency: "Average zone — neutral tendencies", rating: "neutral" },
  "Mark Carlson":       { kRate: "21.3%", bbRate: "8.2%", tendency: "Average zone · consistent calls", rating: "neutral" },
  "Todd Tichenor":      { kRate: "21.0%", bbRate: "8.5%", tendency: "Neutral zone — no strong tendencies", rating: "neutral" },
  "Doug Eddings":       { kRate: "21.0%", bbRate: "8.2%", tendency: "Average zone — neutral environment", rating: "neutral" },
  "Jim Reynolds":       { kRate: "21.0%", bbRate: "8.4%", tendency: "Average zone — neutral for all props", rating: "neutral" },
  "Dan Iassogna":       { kRate: "20.9%", bbRate: "8.4%", tendency: "Solid zone · above-average strike calls", rating: "neutral" },
  "Brian O'Nora":       { kRate: "21.0%", bbRate: "8.5%", tendency: "Average zone — consistent", rating: "neutral" },
  "Sam Holbrook":       { kRate: "21.0%", bbRate: "8.2%", tendency: "Average zone — no notable tendencies", rating: "neutral" },
  "Hunter Wendelstedt": { kRate: "21.0%", bbRate: "8.5%", tendency: "Average zone — neutral calls", rating: "neutral" },
  "Ted Barrett":        { kRate: "21.0%", bbRate: "8.2%", tendency: "Average zone — reliable veteran", rating: "neutral" },
  "Mike Everitt":       { kRate: "21.0%", bbRate: "8.5%", tendency: "Average zone — no prop tendencies", rating: "neutral" },
  "John Tumpane":       { kRate: "21.0%", bbRate: "8.3%", tendency: "Average zone — neutral environment", rating: "neutral" },
  "Lance Barksdale":    { kRate: "20.9%", bbRate: "8.7%", tendency: "Slightly loose zone — watch BB props", rating: "neutral" },
  "Marty Foster":       { kRate: "20.8%", bbRate: "8.9%", tendency: "Average zone — slightly more walks", rating: "neutral" },
  "Scott Barry":        { kRate: "21.0%", bbRate: "8.4%", tendency: "Average zone — neutral calls", rating: "neutral" },
  "Jerry Layne":        { kRate: "20.9%", bbRate: "8.6%", tendency: "Average zone — veteran consistency", rating: "neutral" },
  "Dave Meals":         { kRate: "21.0%", bbRate: "8.5%", tendency: "Neutral zone — consistent career", rating: "neutral" },
  "Paul Nauert":        { kRate: "21.0%", bbRate: "8.2%", tendency: "Average zone — no strong tendencies", rating: "neutral" },
  "Larry Vanover":      { kRate: "20.8%", bbRate: "8.8%", tendency: "Slightly loose zone — neutral overall", rating: "neutral" },
  "Bill Welke":         { kRate: "20.9%", bbRate: "8.6%", tendency: "Average zone — neutral for all props", rating: "neutral" },
  "Jeff Kellogg":       { kRate: "21.0%", bbRate: "8.5%", tendency: "Average zone — neutral tendencies", rating: "neutral" },
  "CB Bucknor":         { kRate: "20.4%", bbRate: "8.6%", tendency: "Inconsistent zone — watch BB props", rating: "neutral" },
  "Mike Winters":       { kRate: "20.3%", bbRate: "9.0%", tendency: "Tight zone — below-average K rate", rating: "hitter" },
  "Bill Miller":        { kRate: "20.2%", bbRate: "9.0%", tendency: "Tight zone — slightly hitter-friendly", rating: "hitter" },
  "Angel Hernandez":    { kRate: "19.2%", bbRate: "9.1%", tendency: "Tight zone — favors pitchers' ERA but suppresses Ks", rating: "hitter" },
  "Ron Kulpa":          { kRate: "19.8%", bbRate: "9.5%", tendency: "Loose zone — watch over on BB props", rating: "hitter" },
  "Joe West":           { kRate: "18.8%", bbRate: "9.8%", tendency: "Slow pace · generous outside corner", rating: "hitter" },
  "Gerry Davis":        { kRate: "19.5%", bbRate: "9.3%", tendency: "Veteran — loose zone, walk-friendly", rating: "hitter" },
};
